FROM openjdk:17-jdk-alpine As builder

ARG TAG_VERSION

COPY gradlew .
COPY gradle gradle
COPY build.gradle.kts .
COPY settings.gradle.kts .
COPY src src

RUN echo "TAG_VERSION: $TAG_VERSION"
RUN ./gradlew -P version=TAG_VERSION clean build


FROM openjdk:17-jdk-alpine
COPY --from=builder build/libs/*.jar app.jar

ENTRYPOINT ["java","-jar","/app.jar"]
