version: '3'

services:
  webapi_blog:
    build:
      context: .
      dockerfile: Dockerfile.webapi_blog
      args:
        - TAG_VERSION=${TAG_VERSION}
    image: webapi/blog:${TAG_VERSION}
    ports:
      - 8080:8080
    restart: always